name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      Solution_Name: ICT3112-Labs.sln
      Test_Project_Path: ICT3112_Calculator\\ICT3112_Calculator.UnitTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Step to build the solution (this ensures that it builds once)
    - name: Build Solution
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # Run NUnit Tests after building the solution
    - name: Run NUnit Tests
      working-directory: ICT3101_Calculator.UnitTests/
      run: dotnet test --no-restore --verbosity normal
      env:
        Configuration: ${{ matrix.configuration }}

    # Run SpecFlow Tests after building the solution
    - name: Run SpecFlow Tests
      working-directory: SpecFlowCalculatorTests/
      run: dotnet test --no-restore --verbosity normal
      env:
        Configuration: ${{ matrix.configuration }}
